### ISSUE TITLE
CMAKE_Swift_COMPILER

### ISSUE THREAD

**Issue by MasterSwift** [compnerd/swift-build-examples#14]
ran ```cmake .``` on the folder

```CMake Error: CMAKE_Swift_COMPILER not set, after EnableLanguage```

What is this suppose to be set to?

**Comment by compnerd** [comment]
It should be set to the path to the swift compiler (swiftc)

**Comment by MasterSwift** [comment]
```set(CMAKE_Swift_COMPILER /usr/local/lib/swiftc)```

same error. tried to even add ```enable_language(Swift)``` before it too

you closed the issue yet didnt even update the project to resemble the correction too.

**Comment by compnerd** [comment]
There’s nothing to update in the project.  This is already documented in the README.md in the subdirectory (HelloWorld-CMake)

**Comment by compnerd** [comment]
Note that you may need to do a clean build (that is remove the existing build directory)

**Comment by MasterSwift** [comment]
yes I did do that before to make sure. cmake supports swift but it seems actually the makefile generator doesn't because the error below precedes the above error . using macOS 

```
CMake Error at /usr/local/Cellar/cmake/3.16.5/share/cmake/Modules/CMakeDetermineSwiftCompiler.cmake:45 (message):
  Swift language not supported by "Unix Makefiles" generator
Call Stack (most recent call first):
  CMakeLists.txt:3 (enable_language)
```

**Comment by compnerd** [comment]
Correct, the only generators that support Swift is the Ninja generator or the Xcode generator on macOS.

**Comment by compnerd** [comment]
Im happy to accept a PR to improve the documentation to make it more obvious that you must use the Ninja generator.
