### ISSUE TITLE
Support for C code?

### ISSUE THREAD

**Issue by atyshka** [compnerd/swift-build-examples#17]
Pretty straightforward question, is linking swift code to C libraries supported?

**Comment by compnerd** [comment]
In what sense?  Do you mean using a C library with a Swift binary?  If so, yes, there is an example in this repository for that.  https://github.com/compnerd/swift-build-examples/tree/master/HelloWorld-CMake

The inverse is a bit trickier.  If you want to integrate a swift library into a C binary, you will need to do the additional work to link in the swift runtime and the startup object as well.  In general, treating the binary as a Swift binary is going to be way easier.

**Comment by atyshka** [comment]
Pardon me if I missed something, but going through that I couldn't find anywhere the CCore library was used within swift... it seemed to just demonstrate that both swift and C could be used within the same CMake project, without demonstrating actual bridging.

**Comment by atyshka** [comment]
This seems like what #9 was looking for... the repo doesn't currently demonstrate linking between languages. That's fine, I'm just wondering if it is possible, i.e. with target_link_libraries

**Comment by compnerd** [comment]
Ah, I see.  That should be easy to rectify and improve.  Feel free to put up a PR for that.  Yes, it is possible in both directions, however, if you want to use `target_link_libraries` to do it easily, the target binary must be Swift.

**Comment by compnerd** [comment]
#19 should be the example that you are looking for.

**Comment by atyshka** [comment]
Thank you for implementing that example! I also saw some code that makes use of module maps, if I can get that working I might submit a PR for that as an alternate solution

**Comment by compnerd** [comment]
You're welcome @atyshka. Sorry, I didn't realize that it was missing in the first place.  Improvements to the examples would be fantastic!

**Comment by atyshka** [comment]
Hm... Looks like your latest commits for this broke the tests for me. Rewinding before them, the test passes just fine.

`[0/1] Running tests...
Test project /home/alex/source-software/swift-build-examples/HelloWorld-CMake/build
    Start 1: TestHelloWorldCore
1/1 Test #1: TestHelloWorldCore ...............***Failed    0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
          1 - TestHelloWorldCore (Failed)
Errors while running CTest
FAILED: CMakeFiles/test.util 
cd /home/alex/source-software/swift-build-examples/HelloWorld-CMake/build && /usr/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.`
