### ISSUE TITLE
Cmake and Ninja Error on Windows

### ISSUE THREAD

**Issue by jacob-sheldon** [compnerd/swift-build-examples#24]
HELLOMINIMAL project

cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=YES

-- The Swift compiler identification is Apple 5.3.2
-- Check for working Swift compiler: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe
-- Check for working Swift compiler: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeTestSwiftCompiler.cmake:41 (message):
  The Swift compiler

    "C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: F:/DEV/swift-cmake-examples-master/HelloMinimal/build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/PROGRA~1/CMake/bin/ninja.exe cmTC_3377c && [1/1] Linking Swift executable cmTC_3377c.exe
    FAILED: cmTC_3377c.exe CMakeFiles/cmTC_3377c.dir/main.swift.obj cmTC_3377c.swiftmodule
    cmd.exe /C "cd . && C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swiftc.exe -output-file-map CMakeFiles\cmTC_3377c.dir\\output-file-map.json -incremental -j 8 -emit-executable -o cmTC_3377c.exe -emit-dependencies    main.swift    && cd ."
    clang: error: no such file or directory: 'C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib\swift\windows\x86_64\swiftrt.obj'
    <unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

-- Configuring incomplete, errors occurred!
See also "F:/DEV/swift-cmake-examples-master/HelloMinimal/build/CMakeFiles/CMakeOutput.log".
See also "F:/DEV/swift-cmake-examples-master/HelloMinimal/build/CMakeFiles/CMakeError.log".

CMakeOutput.log
The system is: Windows - 10.0.18363 - AMD64
Running the Swift compiler: "C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe" -version
compnerd.org Swift version 5.3.2 (swift-5.3.2-RELEASE)
Target: x86_64-unknown-windows-msvc

Running the Swift compiler: "C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe" -version
compnerd.org Swift version 5.3.2 (swift-5.3.2-RELEASE)
Target: x86_64-unknown-windows-msvc

**Comment by compnerd** [comment]
This is expected given the incorrect invocation.  You need to ensure that `-sdk <path to sdk>` (which should be something like `-sdk C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk`).  There is the `%SDKROOT%` environment variable that has the path, and you can do something like:

```cmd
set SWIFTFLAGS=-sdk %SDKROOT%
cmake -B build -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTING=YES -D CMAKE_Swift_FLAGS=%SWIFTFLAGS% -G Ninja -S .
```

Note that the need for release builds is due to the debug Swift standard library not being included, and that will cause run time issues due to a mismatch between the C library ABI.

**Comment by compnerd** [comment]
Bleh; I didn't realize that the instructions didn't cover Windows.  I've updated the documentation at https://github.com/compnerd/swift-cmake-examples/tree/main/HelloWorld that you likely grabbed the commands from.  Could you please report if they help?

**Comment by jacob-sheldon** [comment]
After I used the command `set SWIFTFLAGS=-sdk %SDKROOT`， get result of `echo %SWIFTFLAGS%` is `-sdk C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk`
But when I used `cmake -B build -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTING=YES -G Ninja -S .`, the failure is comming.

-- The C compiler identification is Clang 10.0.0 with GNU-like command-line
-- The Swift compiler identification is Apple 5.3.2
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Swift compiler: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe
-- Check for working Swift compiler: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeTestSwiftCompiler.cmake:41 (message):
  The Swift compiler

    "C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/Administrator/Desktop/swift-cmake-examples/HelloWorld/build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/PROGRA~1/CMake/bin/ninja.exe cmTC_df535 && [1/1] Linking Swift executable cmTC_df535.exe
    FAILED: cmTC_df535.exe CMakeFiles/cmTC_df535.dir/main.swift.obj cmTC_df535.swiftmodule
    cmd.exe /C "cd . && C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swiftc.exe -output-file-map CMakeFiles\cmTC_df535.dir\\output-file-map.json -incremental -j 8 -emit-executable -o cmTC_df535.exe -emit-dependencies    main.swift 
   && cd ."
    clang: error: no such file or directory: 'C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib\swift\windows\x86_64\swiftrt.obj'
    <unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/Desktop/swift-cmake-examples/HelloWorld/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Administrator/Desktop/swift-cmake-examples/HelloWorld/build/CMakeFiles/CMakeError.log".


Likely, there is nothing changed.

**Comment by compnerd** [comment]
Yes, nothing has changed because you need to do a clean build.  You should clear away build (`rd /s /q build`) first.  I should've mentioned that.  Its a quirk of how cached variables work with CMake.

**Comment by jacob-sheldon** [comment]
thanks. But there is still report that error. Even I restart my pc, the error still exists.
Could I use the vscode's cmd terminal to execute cmds?

**Comment by jacob-sheldon** [comment]
I had do my best to try, but i can't find the right way. could you do me a favour?

**Comment by compnerd** [comment]
The VSCode terminal _could_ work, but it may require additional setup to ensure that the VS setup is complete.  If the output is identical, it implies that the swift flags have not been passed to CMake.  Note that you are missing the required argument in the CMake invocation:

```cmd
cmake -B build -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTING=YES -D CMAKE_Swift_FLAGS=%SWIFTFLAGS% -G Ninja -S .
```

**Comment by jacob-sheldon** [comment]
Thanks. I am using the vscode cmd terminal to do this.
Now, I execute `set SWIFTFLAGS=-sdk %SDKROOT%` and `cmake -B build -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTING=YES -D CMAKE_Swift_FLAGS=%SWIFTFLAGS% -G Ninja -S .`
This error changed. Now the error is:
```
It fails with the following output:

    Change Dir: C:/Users/Administrator/Desktop/swift-cmake-examples/HelloWorld/build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/PROGRA~1/CMake/bin/ninja.exe cmTC_8622a && [1/1] Linking Swift executable cmTC_8622a.exe
    FAILED: cmTC_8622a.exe CMakeFiles/cmTC_8622a.dir/main.swift.obj cmTC_8622a.swiftmodule
    cmd.exe /C "cd . && C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swiftc.exe -output-file-map CMakeFiles\cmTC_8622a.dir\\output-file-map.json -incremental -j 8 -emit-executable -o cmTC_8622a.exe -emit-dependencies  C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk  C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk  main.swift    && cd ."
    clang: error: no such file or directory: 'C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib\swift\windows\x86_64\swiftrt.obj'
    <unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)
```
and the CMakeLists.txt:4 in Hellow world project is `project(SwiftDemo LANGUAGES C Swift)`

My VS individual component is the all in swift.org quick start page.
![image](https://user-images.githubusercontent.com/9928255/104144409-12f86780-53fe-11eb-8f79-8828b6a236a6.png)


Do you have any idea about this?

**Comment by compnerd** [comment]
There is something wrong with your invocation still.  I cannot tell what it is because it doesn't show up in the snippets that you've posted.

The swift flags are incorrect.  You are missing `-sdk` in front of the SDKROOT.

**Comment by jacob-sheldon** [comment]
Bingo, i succeed finally.
I find the right way to run it at your other github repo:[swift-build](https://github.com/compnerd/swift-build/blob/master/docs/Windows.md)

Thank you very very very much.
