### ISSUE TITLE
Build HelloWorld and HelloMini failed

### ISSUE THREAD

**Issue by jacob-sheldon** [compnerd/swift-build-examples#25]
On windows, these two projects builed failed using the commands in README.
```cmd
set SWIFTFLAGS=-sdk %SDKROOT%
cmake -B build -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTING=YES -G Ninja -S .
ninja -C build
ninja -C build test
```
following is the fail message:
```
It fails with the following output:

    Change Dir: C:/Users/Administrator/Desktop/swift-cmake-examples/HelloWorld/build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/PROGRA~1/CMake/bin/ninja.exe cmTC_8c91d && [1/1] Linking Swift executable cmTC_8c91d.exe
    FAILED: cmTC_8c91d.exe CMakeFiles/cmTC_8c91d.dir/main.swift.obj cmTC_8c91d.swiftmodule       
    cmd.exe /C "cd . && C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swiftc.exe -output-file-map CMakeFiles\cmTC_8c91d.dir\\output-file-map.json -incremental -j 8 -emit-executable -o cmTC_8c91d.exe -emit-dependencies    main.swift    && cd ."
    clang: error: no such file or directory: 'C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib\swift\windows\x86_64\swiftrt.obj'
    <unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
```

Then i found method in https://github.com/compnerd/swift-build/blob/master/docs/Windows.md,
```
SET INSTALLATION_DIR=C:
SET SDK=%INSTALLATION_DIR%\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk
SET OS=windows
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=YES -D CMAKE_Swift_FLAGS="-sdk %SDK% -I %SDK%/usr/lib/swift -L %SDK%/usr/lib/swift/%OS%"
cd build
ninja
ninja test
```
 use this method HelloWorld build success : `Hello World!`, but HelloMini still failed. and the fail message is:
```
FAILED: HiKit.lib CMakeFiles/HiKit.dir/hikit.swift.obj HiKit.swiftmodule 
cmd.exe /C "cd . && C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swiftc.exe -output-file-map CMakeFiles\HiKit.dir\RelWithDebInfo\output-file-map.json -incremental -j 8 -emit-library -static -o HiKit.lib -module-name HiKit -module-link-name HiKit -emit-module -emit-module-path HiKit.swiftmodule -emit-dependencies  -sdk C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk -I C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk/usr/lib/swift -L C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk/usr/lib/swift/windows -O -g  ..\hikit.swift    && cd ."
<unknown>:0: error: unable to execute command: <unknown>
ninja: build stopped: subcommand failed.
```

**Comment by compnerd** [comment]
The error message doesn't indicate what failed.  I suspect that you are not using the Visual Studio Developer Command Prompt but rather a regular command prompt or PowerShell.  Can you please provide the output of the verbose run of the driver so we can identify which command is failing to run.

**Comment by jacob-sheldon** [comment]
before i used vs code command prompt.
now when i use x64 Native Tools Command Prompt for VS 2019, I get a new fail message.
![image](https://user-images.githubusercontent.com/9928255/104976052-4018cb80-5a37-11eb-9c36-ac44ecaa1848.png)

I used this command:

**Comment by compnerd** [comment]
Okay, the new version looks better; unfortunately, I cannot make out the error, can you please change the language to english?  It seems that its failing to find a symbol from HiKit

**Comment by compnerd** [comment]
Ugh, I see the issue; passing `-D BUILD_SHARED_LIBS=YES` should fix the issue.

**Comment by jacob-sheldon** [comment]
Yes, it's done by add `-D BUILD_SHARED_LIBS=YES` In `cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=YES -D BUILD_SHARED_LIBS=YES -D CMAKE_Swift_FLAGS="-sdk %SDK% -I %SDK%/usr/lib/swift -L %SDK%/usr/lib/swift/%OS%"`. Thank you.

I have somequestion, could you help me?

First, why only me get this error? Is there any config error in my computer?
Second, why there is still report an error using the command `cmake -B build -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTING=YES -D BUILD_SHARED_LIBS=YES -G Ninja -S .` in README still failed.
Third, I want to learn some knowledge about swift compiler, so that I could solve some problem when I got other errors next time, but I don't know how and where to get these knowleage, please teach me. 

Thanks.

**Comment by compnerd** [comment]
> First, why only me get this error? Is there any config error in my computer?

Because you missed the various documents all which explain that you must link dynamically on Windows (and Darwin).  The documentation explains that, its not a system issue, its an issue with the usage.

> Second, why there is still report an error using the command cmake -B build -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTING=YES -D BUILD_SHARED_LIBS=YES -G Ninja -S . in README still failed.

I don't understand this question.  It sounds like it already built, so without more details, I dont know what error you are referring to here.

> Third, I want to learn some knowledge about swift compiler, so that I could solve some problem when I got other errors next time, but I don't know how and where to get these knowleage, please teach me.

This is very open ended, I don't think that this is reasonable.  However, the issues here have nothing to do so with the compiler but more with reading/following existing documentation.  Alternatively, it could be that there are specifics in the documentation which can be improved, but that is often lost on those who are working on the project.  Working to improve documentation would be a good way to learn.
