### ISSUE TITLE
Failed to compile HelloWorld

### ISSUE THREAD

**Issue by Hxsyed** [compnerd/swift-build-examples#27]
Hey there @compnerd , I am trying to compile, the Hello World app on windows and I am running into errors. Attached below are screenshots of my HelloMinimal running, but HelloWorld failing to compile. 
![Capture](https://user-images.githubusercontent.com/63178444/123459326-25351f00-d5b4-11eb-9537-418b912234a1.PNG)
![Capture2](https://user-images.githubusercontent.com/63178444/123459331-26664c00-d5b4-11eb-99e4-2ba1d04515eb.PNG)

**Comment by compnerd** [comment]
I think that you are not following the instructions or you have some other changes to the repository.  This works file for me locally at the top of tree:
```
>cmake -B out -D CMAKE_Swift_COMPILER=S:/b/1/bin/swiftc.exe -D CMAKE_BUILD_TYPE=Release -G Ninja -S .
-- The C compiler identification is MSVC 19.29.30037.0
-- The Swift compiler identification is Apple 5.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Swift compiler: S:/b/1/bin/swiftc.exe
-- Check for working Swift compiler: S:/b/1/bin/swiftc.exe - works
-- Configuring done
-- Generating done
-- Build files have been written to: S:/tmp/swift-cmake-examples/HelloWorld/out
```

What is interesting is that your screenshot shows no configuration occurring when building the project, which leads me to believe that you either have modifications to your tree or you had a previous build and you did not clean that up.

**Comment by Hxsyed** [comment]
Thanks for the fast response @compnerd . Yeah, I have followed the instruction that u have provided in the documentation, when i was building HelloMinimal, I have seen the configuration occurring one time when it was successfully built. Any idea what I should do next?

**Comment by compnerd** [comment]
Without the full logs its unclear.  I suspect that it is because you are trying to build over an existing build.  I would suggest that you read up on CMake at https://cmake.org/cmake/help/latest if you are trying to use CMake.

**Comment by Hxsyed** [comment]
Hey @compnerd hope u had a great weekend, I have made a folder with the Cache, output and error logs and provided a link have a look. The cache includes the tree that u were mentioning. I found that I had two build folders, so I deleted them both and recompiled and this is what my configuration looks like. 

![image](https://user-images.githubusercontent.com/63178444/123702334-fc6d8d80-d830-11eb-86a2-647ee3101a36.png)

I was facing the executable error but now I am facing the target error, but I am sure since it works in your end I don't have to make changes to the CMakeLists file right? I hope this provides some more info on my error I am facing. I used forward slashes because I read that backslashes backslashes causes bugs ( https://gitlab.kitware.com/cmake/cmake/-/issues/20180).  

Link: https://drive.google.com/drive/folders/1wtT9k0NowAYNQ1w-1D3OLlc1l7zL9MqW?usp=sharing

**Comment by compnerd** [comment]
The fact that the only output is `-- Configuring done` means that the configure step did not occur, you have cached values which are going to give you invalid results.  Please do this again with a clean build.  I don't think that the path to the compiler should even be 100% necessary with the recent improvements.  A simple `cmake -B out -D CMAKE_BUILD_TYPE=Release -G Ninja -S .` should be sufficient as it should pick up everything that it needs.

**Comment by compnerd** [comment]
Wait, I just had another look at the screenshot and I missed it the first two times.  You are not following the instructions!  You _really_ should read up on CMake.  You are invoking CMake in the wrong directory.  The top level directories (`BuildDependencies`, `HelloMinimal` and `HelloWorld`) are the only ones that you can invoke CMake under.  They are the project roots.

This repository is meant as a collection of examples, and is thus a collection of 3 different repositories bundled into one.  You always run cmake at the _top_ of the project, of which there are three listed above.

**Comment by Hxsyed** [comment]
Thank you, I got it to work.
