### ISSUE TITLE
Problems while using on macOS

### ISSUE THREAD

**Issue by Grivus** [compnerd/swift-build-examples#8]
Hi!

I'm trying to build the example on macOS 10.14 with xCode 10.2, and it seems broken for me.
First of all, cmake does not seems to support the version in the way it written: 

`Devs-Mac-mini:swift-cmake-demo developer$ pwd`
`/Users/developer/Documents/swift-cmake-demo`
`Devs-Mac-mini:swift-cmake-demo developer$ cmake .`
`CMake Error at CMakeLists.txt:2 (cmake_minimum_required):`
  `CMake 3.15.20190814 or higher is required.  You are running version 3.15.5`

When I changed the required version to 3.15.2 (which is not totally correct, I know), it allows me to generate the project. 

The project SwiftDemo.xcodeproj which is generated I could open, but it could not be built.

It throws Swift compile error "No such module HelloWorldCore in TestHelloWorldCore.swift:3", same but in HelloWorld.swift:2, and 'Expression is not allowed at the top level in HelloWorld.swift' on line 23 (main())

I noticed that Swift language version in Xcode project differs from the one, that stated in cmakelists: it is 4 vs 4.2, but switching this version does not resolves the problem. 

I'm not a proficient Swift developer, so I hope somebody could help me to run this demo.

**Comment by compnerd** [comment]
This is not meant to be used with Xcode, only Ninja.  If it fails with ninja, please reopen the issue.
